name: Publish and Install Helm Charts

on:
  push:
    branches: ['main', 'dev', 'stage']
  workflow_dispatch:
    inputs:
      chart_name:
        type: string
        description: 'Chart name to install'
        required: true
        default: "spring-demo"
      release_name:
        type: string
        description: 'Helm release name'
        required: false
      namespace:
        type: string
        description: 'Kubernetes namespace'
        required: false

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Package Helm Charts
        run: |
          mkdir -p packaged_charts
          for dir in */ ; do
            if [ -f "${dir}Chart.yaml" ]; then
              echo "Packaging chart in directory: $dir"
              helm dependency update "$dir"
              helm package "$dir" --destination packaged_charts
            fi
          done

      - name: Update Helm Repository Index
        run: |
          helm repo index packaged_charts --url https://org-sam.github.io/helm-charts/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packaged_charts
          publish_branch: gh-pages
          force_orphan: true

  install:
    runs-on: ubuntu-latest
    needs: publish
    if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/stage'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add Helm Repository
        run: |
          helm repo add org-sam-charts https://org-sam.github.io/helm-charts/
          helm repo update

      - name: Pull and Install Helm Chart
        run: |
          # Determine the branch name
          BRANCH_NAME="${{ github.ref_name }}"

          # Map branch name to values file
          case "$BRANCH_NAME" in
            dev)
              VALUES_FILE="dev.yaml"
              ;;
            stage)
              VALUES_FILE="stage.yaml"
              ;;
            master|main)
              VALUES_FILE="master.yaml"
              ;;
            *)
              echo "Unknown branch $BRANCH_NAME. Using default values."
              VALUES_FILE=""
              ;;
          esac

          # Get inputs from workflow_dispatch or set defaults
          CHART_NAME="${{ github.event.inputs.chart_name }}"
          RELEASE_NAME="${{ github.event.inputs.release_name }}"
          NAMESPACE="${{ github.event.inputs.namespace }}"

          if [ -z "$CHART_NAME" ]; then
            echo "Error: chart_name input is required."
            exit 1
          fi

          if [ -z "$RELEASE_NAME" ]; then
            RELEASE_NAME="my-release"
          fi

          if [ -z "$NAMESPACE" ]; then
            NAMESPACE="default"
          fi

          # Pull the chart and untar
          helm pull org-sam-charts/"$CHART_NAME" --untar

          # Install the chart from local directory
          if [ -n "$VALUES_FILE" ]; then
            helm install "$RELEASE_NAME" "$CHART_NAME" --namespace "$NAMESPACE" --values "$CHART_NAME/$VALUES_FILE"
          else
            helm install "$RELEASE_NAME" "$CHART_NAME" --namespace "$NAMESPACE"
          fi
