name: Workflow 2

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  package-and-push-charts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Package Helm Charts
      run: |
        mkdir -p charts
        for dir in */; do
          if [ -d "$dir" ]; then
            helm package $dir --destination charts/
          fi
        done

    - name: Push to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./charts
        publish_branch: gh-pages  # Certifique-se de configurar o GitHub Pages com este branch
