name: Workflow 3

on:
  push:
    branches:
      - main
      - master

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
        IMAGE_REPO: "${{ github.repository }}/${{ github.ref_name }}"
        URI_ECR: "${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-oicd
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Package Helm charts
        run: |
          mkdir -p packaged-charts
          for dir in charts/*/; do
            helm package "$dir" --destination ./packaged-charts
          done

      - name: Push Helm charts to ECR
        run: |
          for chart in packaged-charts/*.tgz; do
            helm push "$chart" oci://${{ env.URI_ECR }}/helm-charts
          done
