name: Workflow 3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
        URI_ECR: "${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-oicd
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Package and push Helm Charts
        run: |
          for chart in $(ls -d */); do
            CHART_NAME=$(basename $chart)
            BRANCH=$(echo ${{ github.ref }} | awk -F'/' '{print $NF}')
            helm package $chart
            helm push $CHART_NAME-*.tgz oci://${{ env.URI_ECR }}/${{ env.ECR_REPO_PREFIX }}/$CHART_NAME/$BRANCH
          done
