name: Workflow 3

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  lint-syntax:
    name: Lint and Test Helm Charts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Helm and Plugins
        run: helm plugin install https://github.com/quintush/helm-unittest

      - name: Lint Helm charts
        run: |
          for app in $(ls -d */); do
            if [ -f "$app/Chart.yaml" ]; then
                helm lint $app -f ./$app/${{ github.ref_name }}.yaml --quiet   
            fi
          done
             

  push:
    runs-on: ubuntu-latest
    needs: [lint-syntax]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-oicd
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sincroniza com S3
        run: aws s3 sync . s3://platos-helm-charts --delete --exclude ".*"

  install:
    needs: [push]
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-oicd
          aws-region: ${{ vars.AWS_REGION }}
      
      - name: Pull S3
        run: aws s3 cp s3://platos-helm-charts/spring-demo spring-demo --recursive
