name: Workflow 3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
        URI_ECR: "${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Package Helm Charts
        run: |
          mkdir -p packaged-charts
          for dir in */ ; do
            if [ -f "$dir/Chart.yaml" ]; then
              helm package "$dir" --destination packaged-charts
            fi
          done

      - name: Generate Helm Repo Index
        run: |
          helm repo index packaged-charts --url https://org-sam.github.io/helm-charts/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packaged-charts
          publish_branch: gh-pages

      - name: Push Charts to GitHub Packages
        run: |
          for chart in packaged-charts/*.tgz; do
            helm push "$chart" org-sam-helm
          done
