name: Workflow 3

on:
  push:
    branches:
      - main  # ou a branch que você desejar

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
        URI_ECR: "${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-oicd
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Package and Push Helm Charts
        env:
          ECR_REGISTRY: ${{ env.URI_ECR }}/helm-charts
        run: |
          # Faça login com helm para ECR
          helm registry login -u AWS -p $(aws ecr get-login-password --region ${{ vars.AWS_REGION }}) $ECR_REGISTRY

          # Iterar sobre cada diretório de chart
          for chart in $(ls -d */ | cut -f1 -d'/'); do
            echo "Packaging chart $chart"
            helm package $chart --destination /tmp

            CHART_PACKAGE=$(ls /tmp/${chart}-*.tgz | head -n1)

            echo "Pushing chart $CHART_PACKAGE to ECR"
            helm push $CHART_PACKAGE oci://$ECR_REGISTRY
          done
