name: Workflow 3

on:
  push:

permissions:
  id-token: write
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-oicd
          aws-region: ${{ vars.AWS_REGION }}

      - name: Sincroniza com S3
        run: aws s3 sync . s3://platos-helm-charts --delete --exclude ".*"

  install:
    needs: [push]
    runs-on: ubuntu-latest
    steps:
      - name: MKDIR
        run: mkdir arquivos-s3
      - name: Pull S3
        run: aws s3 cp s3://platos-helm-charts/spring-demo ./arquivos-s3/spring-demo --recursive
      - name: LS
        run: ls -l ./arquivos-s3/spring-demo
      
      - name: create kind cluster
        run: kind create cluster --wait 30s

      - name: Install helm
        run: |
          helm upgrade spring-demo ./arquivos-s3/spring-demo \
            -f ./arquivos-s3/spring-demo/dev.yaml \
            --atomic \
            --install \
            --debug \
            --namespace spring-demo \
            --set image="nginx" \
            --set tagsDatadogVersion="v${{ github.run_id }}" \
            --set ddGitCommitSHA="${{ github.sha }}" \
            --set ddGitRepositoryURL="https://github.com/${{ github.repository }}" \
            --timeout 10m

      
