name: Workflow 4

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-oicd
          aws-region: ${{ vars.AWS_REGION }}
      
  
      # 5. Pacotar os Helm charts
      - name: Pacotar Helm charts
        run: |
          mkdir packaged-charts
          for dir in */ ; do
            if [ -f "$dir/Chart.yaml" ]; then
              helm package "$dir" --destination packaged-charts
            fi
          done

      # 6. Inicializar o repositório Helm no S3 (somente na primeira execução)
      - name: Inicializar Repositório Helm no S3
        run: |
          helm s3 init s3://platos-helm-charts

      # 7. Atualizar o repositório Helm no S3 com os novos charts
      - name: Atualizar Repositório Helm no S3
        run: |
          for chart in packaged-charts/*.tgz; do
            helm s3 push "$chart" s3://platos-helm-charts
          done
