name: Publish Helm Charts to ECR

on:
  push:
    branches: ['main']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  push-helm-charts:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/github-oicd
            aws-region: ${{ vars.AWS_REGION }}

        - name: Login to Amazon ECR - 1
          uses: aws-actions/amazon-ecr-login@v2        

        - name: Ensure ECR Repository Exists
          run: |
            for app in $(ls -d */); do
                if [ -f "$app/Chart.yaml" ]; then
                    REPO_NAME=${app%/}
                    aws ecr describe-repositories --repository-names "$REPO_NAME" > /dev/null || \
                    aws ecr create-repository --repository-name "$REPO_NAME"
                fi
            done
        
        - name: Authenticate your Helm client to the Amazon ECR registry
          run: |
            aws ecr get-login-password \
            --region ${{ vars.AWS_REGION }} | helm registry login \
            --username AWS \
            --password-stdin ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.region.amazonaws.com
        
        # - name: Habilitar OCI para Helm
        #   run: |
        #     helm registry login -u AWS --password-stdin https://${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com          

        - name: Empacotar e Enviar Charts
          run: |
            for app in $(ls -d */); do
                if [ -f "$app/Chart.yaml" ]; then
                    helm package $app --destination .
                    helm push ${app%/}-*.tgz oci://${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/$app
                fi
            done

